# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
      timezone: Asia/Jakarta
      # Specify labels for `gha` pull requests
    labels:
      - "\U0001F517 dependencies"
      - "\U0001F517 dependencies:github-actions"
      - "\U0001F916 automation"
    commit-message:
      # Prefix all commit messages with `chore` (follow conventional-commits)
      # include a list of updated dependencies
      prefix: chore
      include: scope
      # Allow up to N open pull requests (0 to disable)
    open-pull-requests-limit: 10
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot/github_actions/actions/checkout-2.3.1`
      separator: /
    # Add the arrays of assignees and reviewers
    assignees:
      - infinitedim/maintainers
    reviewers:
      - infinitedim/reviewers
